### ISSUE TITLE
Extra configuration files from Nemo model

### ISSUE THREAD

**Issue by giannisp-verneek** [dusty-nv/jetson-voice#3]
I'm doing some ASR tests and I want to use a different model than the ones offered here. I used the `nemo_export_onnx` script which produces an `onnx` and a single `json` file. Any of the other jsons and binaries from the models you offer are not generated. Is this the expected behavior?

How can I check that the transformation is done correctly?

**Comment by lmirel** [comment]
an year later I'm looking for the answer to the same question. did you manage to generate the other files required to run ASR?
thanks

**Comment by kurkovpavel** [comment]
*.onnx and *.json are enough for run model with greedy decoder. If you want beamsearch decoder you should prepare your language model LM and compile it with kenlm to get lm.bin
